services:
  privatecaptcha:
    image: ghcr.io/privatecaptcha/privatecaptcha:v0.0.10
    depends_on:
      migration:
        condition: service_completed_successfully
    ports:
      - 127.0.0.1:8080:8080
    environment:
      - STAGE=prod
      - PC_POSTGRES=postgres://postgres:postgres@postgres:5432/privatecaptcha?search_path=backend
      - PC_CLICKHOUSE_HOST=clickhouse
      - PC_CLICKHOUSE_DB=privatecaptcha
      - PC_CLICKHOUSE_USER=default
      - PC_CLICKHOUSE_PASSWORD=
      # ---- required ----
      - PC_PORTAL_BASE_URL=${PC_PORTAL_BASE_URL}
      - PC_API_BASE_URL=${PC_API_BASE_URL}
      - PC_CDN_BASE_URL=${PC_CDN_BASE_URL}
      - PC_ADMIN_EMAIL=${PC_ADMIN_EMAIL}
      - PC_EMAIL_FROM=${PC_EMAIL_FROM}
      - PC_RATE_LIMIT_HEADER=${PC_RATE_LIMIT_HEADER}
      - PC_USER_FINGERPRINT_KEY=${PC_USER_FINGERPRINT_KEY}
      - PC_API_SALT=${PC_API_SALT}
      - SMTP_ENDPOINT=${SMTP_ENDPOINT}
      - SMTP_USERNAME=${SMTP_USERNAME}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      # ---- optional ----
      - PC_LOCAL_ADDRESS
      - PC_REGISTRATION_ALLOWED
      - PC_HEALTHCHECK_INTERVAL
      - PC_RATE_LIMIT_RPS
      - PC_RATE_LIMIT_BURST
      - PC_VERBOSE
    networks:
      - postgres_network
      - clickhouse_network
      - server_network

  migration:
    image: ghcr.io/privatecaptcha/privatecaptcha:v0.0.10
    command:
      /app/server -mode migrate -migrate-hash ignore
    environment:
      - STAGE=prod
      - PC_POSTGRES=postgres://postgres:postgres@postgres:5432/privatecaptcha?search_path=public
      - PC_CLICKHOUSE_HOST=clickhouse
      - PC_CLICKHOUSE_DB=privatecaptcha
      - PC_CLICKHOUSE_USER=default
      - PC_CLICKHOUSE_PASSWORD=
      - PC_PORTAL_BASE_URL=${PC_PORTAL_BASE_URL}
      - PC_ADMIN_EMAIL=${PC_ADMIN_EMAIL}
    depends_on:
      postgres:
        condition: service_healthy
      clickhouse:
        condition: service_healthy
    networks:
      - postgres_network
      - clickhouse_network

  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: privatecaptcha
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: pg_isready -U postgres -d privatecaptcha
      interval: 3s
      timeout: 3s
      retries: 3
    networks:
      - postgres_network
    volumes:
      - ./init/postgres.sql:/docker-entrypoint-initdb.d/init.sql:ro
      - postgres_data_volume:/var/lib/postgresql/data

  clickhouse:
    image: clickhouse/clickhouse-server:24.12.6-alpine
    environment:
      CLICKHOUSE_DB: privatecaptcha
      CLICKHOUSE_SKIP_USER_SETUP: 1
    networks:
      - clickhouse_network
    healthcheck:
      test: wget --no-verbose --tries=1 -O - http://0.0.0.0:8123/?query=SELECT%201 || exit 1
      interval: 3s
      timeout: 3s
      retries: 3
    volumes:
      - ./clickhouse/clickhouse-config.xml:/etc/clickhouse-server/config.d/myconfig.xml:ro
      - clickhouse_data_volume:/var/lib/clickhouse
    ulimits:
      nofile:
        soft: 262144
        hard: 262144

networks:
  postgres_network:
  clickhouse_network:
  server_network:

volumes:
  postgres_data_volume:
  clickhouse_data_volume:
